### ISSUE TITLE
.htaccess is ignored

### ISSUE THREAD

**Issue by norbertpy** [jfmatth/openshift-django17#10]
For some reason having an `.htaccess` file to redirect HTTP to HTTPS does not work on OpenShift. Based on https://help.openshift.com/hc/en-us/articles/202398810-How-to-redirect-traffic-to-HTTPS- placing `.htaccess` in `wsgi` folder or repo root should redirect all of the traffic to HTTPS. But it doesn't.

Do you have any idea?

**Comment by jfmatth** [comment]
Well, i'm still getting used to all this git / branching / tagging stuff, and the update the closed this ticket doesn't show the essence of what I changed.

Basically, I move the mysite/wsgi.py to wsgi/wsgi.py and updated the README.md accordingly.  

I was trying to keep the django startproject files as pure as possible, but due to the 'bug' in OS, i'll change my repo for now.  I'll open a bug report with RH soon enough, but wanted to get this fix out there ASAP for anyone who needs it..

**Comment by arkashkin1** [comment]
Thank you!
